### PR TITLE
Constructor Property version php 8

### PR DESCRIPTION
**Pull request by idanieldrew**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like the tests are failing, could you take a look at that?

**Comment by freekmurze** [comment]
Closing due to inactivity.

**Comment by Tofandel** [comment]
Btw the tests are failling because symfony/finder was bumped to php8.1 and it seems the test on php8 is using the new version anyways

**Comment by Tofandel** [comment]
Okay so it's because laravel 9 has also bumped to symfony v6 and php8.1 so the tests for stable l9 php8.0 will always fail

**Comment by Tofandel** [comment]
Either there shouldn't be an --ignore-platform-reqs

Or the matrix should be updated to exlude l9 php8.0

**Pull request closed without merging**
